### ISSUE TITLE
Explore full text search with Hibernate Search 6 + SQL + Elasticsearch

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1101]
This this SO post: [How to implement full text search in Spring Boot with JPA + MySQL](https://stackoverflow.com/questions/57683004/how-to-implement-full-text-search-in-spring-boot-with-jpa-mysql)

It may also be worth looking at OpenSearch, the open-source alternative to Elasticsearch:

> For starters, the primary language for OpenSearch queries is Query DSL. However, there are also two plugins that allow you to use two other querying languages: SQL and PPL (Piped Processing Language). 

[Source](https://logz.io/blog/opensearch-queries/)

Hibernate Search 6 seems to [support](https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/) OpenSearch.

> Every section of this documentation referring to Elasticsearch is also relevant for the OpenSearch distribution.

See also:

- [Elasticsearch Queries: A Guide to Query DSL](https://logz.io/blog/elasticsearch-queries/)
- [OpenSearch Queries: Query DSL and Beyond](https://logz.io/blog/opensearch-queries/)
- [Hibernate Search 6 With Spring Boot (uses Lucene)](https://www.mindbowser.com/hibernate-search-6-with-spring-boot/)
- [From table to index (and back) with Hibernate Search 6](https://yrodiere.github.io/presentation/hsearch-fosdem-2019)
- [Guide to Hibernate Search](https://howtodoinjava.com/hibernate/hibernate-search/)
- https://gauthier-cassany.com/posts/spring-boot-hibernate-search
- https://gauthier-cassany.com/posts/spring-boot-paginated-search
  - https://github.com/Mozenn/spring-boot-hibernate-search
- [Full-Text Search with Hibernate Search and Spring Boot](https://reflectoring.io/hibernate-search/)
  - Shows how to load existing data into elasticsearch
- [Hibernate Search 6 With Spring Boot](https://www.mindbowser.com/hibernate-search-6-with-spring-boot/) (Hibernate Search 6)
  - Shows how to load existing data into elasticsearch

**Comment by tschaffter** [comment]
https://github.com/hibernate/hibernate-search

**Comment by tschaffter** [comment]
https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#getting-started-configuration

**Comment by tschaffter** [comment]
This [table](https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#getting-started) seems to say that I should use opensearch 1.2.x and not 1.3.x.

**Comment by tschaffter** [comment]
## Issue with the function name `searchBy`

```console
Failed to create query for method public abstract java.util.List org.sagebionetworks.challenge.model.repository.SearchRepository.searchBy(java.lang.String,int,java.lang.String[])! At least 1 parameter(s) provided but only 0 parameter(s) present in query.
```

**Comment by tschaffter** [comment]
## Get info from Elasticsearch

### Get list of indexes

```console
http://localhost:9200/_cat/indices?format=json
```

**Comment by tschaffter** [comment]
## Indexing entities with Hibernate Search

Logs:

```console
2023-01-04 21:25:14.000  INFO 20406 --- [  restartedMain] o.s.c.c.HibernateSearchIndexBuild        : Started Initializing Indexes
2023-01-04 21:25:14.030  WARN 20406 --- [port thread - 1] org.elasticsearch.client.RestClient      : request [POST http://challenge-registry-opensearch:9200/challenge-registry-challenge-write/_refresh] returned 1 warnings: [299 Elasticsearch-7.17.8-120eabe1c8a0cb2ae87cffc109a5b65d213e9df1 "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
2023-01-04 21:25:14.052  WARN 20406 --- [port thread - 1] org.elasticsearch.client.RestClient      : request [POST http://challenge-registry-opensearch:9200/challenge-registry-challenge-write/_delete_by_query?conflicts=proceed] returned 1 warnings: [299 Elasticsearch-7.17.8-120eabe1c8a0cb2ae87cffc109a5b65d213e9df1 "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
2023-01-04 21:25:14.063  WARN 20406 --- [port thread - 1] org.elasticsearch.client.RestClient      : request [POST http://challenge-registry-opensearch:9200/challenge-registry-challenge-write/_forcemerge] returned 1 warnings: [299 Elasticsearch-7.17.8-120eabe1c8a0cb2ae87cffc109a5b65d213e9df1 "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
2023-01-04 21:25:14.235  INFO 20406 --- [ ID loading - 0] s.m.p.m.i.PojoMassIndexingLoggingMonitor : HSEARCH000027: Mass indexing is going to index 3 entities.
2023-01-04 21:25:14.321  WARN 20406 --- [port thread - 3] org.elasticsearch.client.RestClient      : request [POST http://challenge-registry-opensearch:9200/_bulk] returned 1 warnings: [299 Elasticsearch-7.17.8-120eabe1c8a0cb2ae87cffc109a5b65d213e9df1 "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
2023-01-04 21:25:14.327  WARN 20406 --- [port thread - 2] org.elasticsearch.client.RestClient      : request [POST http://challenge-registry-opensearch:9200/_bulk] returned 1 warnings: [299 Elasticsearch-7.17.8-120eabe1c8a0cb2ae87cffc109a5b65d213e9df1 "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
2023-01-04 21:25:14.332  WARN 20406 --- [port thread - 1] org.elasticsearch.client.RestClient      : request [POST http://challenge-registry-opensearch:9200/_bulk] returned 1 warnings: [299 Elasticsearch-7.17.8-120eabe1c8a0cb2ae87cffc109a5b65d213e9df1 "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
2023-01-04 21:25:14.373  WARN 20406 --- [port thread - 1] org.elasticsearch.client.RestClient      : request [POST http://challenge-registry-opensearch:9200/challenge-registry-challenge-write/_flush] returned 1 warnings: [299 Elasticsearch-7.17.8-120eabe1c8a0cb2ae87cffc109a5b65d213e9df1 "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
2023-01-04 21:25:14.381  WARN 20406 --- [port thread - 1] org.elasticsearch.client.RestClient      : request [POST http://challenge-registry-opensearch:9200/challenge-registry-challenge-write/_refresh] returned 1 warnings: [299 Elasticsearch-7.17.8-120eabe1c8a0cb2ae87cffc109a5b65d213e9df1 "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
2023-01-04 21:25:14.382  INFO 20406 --- [  restartedMain] s.m.p.m.i.PojoMassIndexingLoggingMonitor : HSEARCH000028: Mass indexing complete. Indexed 3 entities.
2023-01-04 21:25:14.382  INFO 20406 --- [  restartedMain] o.s.c.c.HibernateSearchIndexBuild        : Completed Indexing
```

Entities:

```console
http://localhost:9200/challenge-registry-challenge-000001/_search?q=*:*
```

```json
{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 3,
      "relation": "eq"
    },
    "max_score": 1.0,
    "hits": [
      {
        "_index": "challenge-registry-challenge-000001",
        "_type": "_doc",
        "_id": "1",
        "_score": 1.0,
        "_source": {
          "name": "The Digital Mammography DREAM Challenge",
          "_entity_type": "ChallengeEntity"
        }
      },
      {
        "_index": "challenge-registry-challenge-000001",
        "_type": "_doc",
        "_id": "2",
        "_score": 1.0,
        "_source": {
          "name": "Patient Mortality EHR DREAM Challenge",
          "_entity_type": "ChallengeEntity"
        }
      },
      {
        "_index": "challenge-registry-challenge-000001",
        "_type": "_doc",
        "_id": "3",
        "_score": 1.0,
        "_source": {
          "name": "COVID-19 EHR DREAM Challenge",
          "_entity_type": "ChallengeEntity"
        }
      }
    ]
  }
}
```

**Comment by tschaffter** [comment]
### Issue retrieving entities with the repository

Error:

```console
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor.intercept(ByteBuddyInterceptor.java:56)
        at org.hibernate.proxy.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:95)
        at org.sagebionetworks.challenge.model.entity.SimpleChallengePlatformEntity$HibernateProxy$8niPjWpX.toString(Unknown Source)
        at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453)
        at org.sagebionetworks.challenge.model.entity.ChallengeEntity.toString(ChallengeEntity.java:25)
        at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453)
        at org.sagebionetworks.challenge.model.entity.ChallengeSubmissionTypeEntity.toString(ChallengeSubmissionTypeEntity.java:20)
        at java.base/java.lang.String.valueOf(String.java:4218)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
        at org.hibernate.collection.internal.PersistentBag.toString(PersistentBag.java:622)
        at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453)
        at org.sagebionetworks.challenge.model.entity.ChallengeEntity.toString(ChallengeEntity.java:25)
        at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453)
        at org.sagebionetworks.challenge.model.entity.ChallengeSubmissionTypeEntity.toString(ChallengeSubmissionTypeEntity.java:20)
        at java.base/java.lang.String.valueOf(String.java:4218)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
        at org.hibernate.collection.internal.PersistentBag.toString(PersistentBag.java:622)
...
```

**Comment by tschaffter** [comment]
## Combining queries

- [Baeldung - Combining Queries](https://www.baeldung.com/hibernate-search#5-phrase-queries) (Hibernate Search 5)
