### ISSUE TITLE
Create minimal, extensible example of base Schematic

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1208]

**Comment by vpchung** [comment]
For this exercise, I created a schema based on our current [Challenge model](https://github.com/Sage-Bionetworks/sage-monorepo/blob/515db23f619b1a52780a75b5387a5cd01af2c2e0/libs/openchallenges/api-client-angular/src/lib/model/challenge.ts) and a select number of its properties:

* Challenge Name - to showcase schematic's `unique` validation rule
* Challenge Description
* Challenge Tags - to showcase schematic's `list like` validation rule (in other words, being able to pass a list of values)
* Challenge Status - to showcase schematic's enforcement of valid values

The result of the Challenge component looks something like this:

Attribute|Description|Valid Values|DependsOn|Required|Properties|Parent|DependsOn Component|Source|Validation Rules
--|--|--|--|:--:|--|--|--|--|:--:
Challenge|A challenge| |"Challenge Name, Challenge Description, Challenge Tags, Challenge Status"| | | | | |
Challenge Name|Name of the challenge| | |TRUE| | | | |unique
Challenge Description|Summary of the challenge| | |TRUE| | | | | |
Challenge Tags|Keywords for the challenge| | |FALSE| | | | |list like
Challenge Status|Current status of the challenge|"upcoming, active, closed"| |TRUE| | | | | |

This schema is then converted into a JSON-LD with schematic's `convert` command:

```
$ schematic schema convert ~/Desktop/challenge_component.csv
```

Afterward, I created a sample manifest with 3 dummy challenges:

Challenge Name|Challenge Description|Challenge Tags|Challenge Status
--|--|--|--
Awesome Challenge|Join us in this awesome challenge! We have cookies.|awesome;cookies|upcoming
Awesome Challenge|We aso hav cukes|awesome;cookies|coming soon
I-Know-Nothing Challenge| | |

> **Fun detail (but not at all important)**: Harper sounded out and spelled the second challenge's description 😆 

I expect the manifest to have one valid row and two invalid:

Row | Attribute | Expected Error
--|--|--
1 | _None_ | _N/A_
2 | `Challenge Name` | Not unique
2 | `Challenge Status` | Invalid value used
3 | `Challenge Description` | Required, but missing
3 | `Challenge Status` | Required, but missing

Putting it to the test, I then ran the manifest through validation with schematic's `validate` command:

```
$ schematic model -c test_config.yml validate -mp ~/Desktop/challenge_manifest.csv -dt Challenge
Starting schematic...
The (model > input > location) argument with value '/Users/vchung/Desktop/challenge_component.jsonld' is being read from the config file.
The (model > input > file_type) argument with value 'local' is being read from the config file.
JSON schema successfully generated from schema.org schema!
JSON schema file log stored as /Users/vchung/Desktop/challenge_component.Challenge.schema.json
FileDataContext loading zep config
GxConfig.parse_yaml() failed with errors - [{'loc': ('xdatasources',), 'msg': 'field required', 'type': 'value_error.missing'}]
GxConfig.parse_yaml() returning empty `xdatasources`
Loading 'datasources' ->
{}
Loaded 'datasources' ->
{}
EphemeralDataContext has not implemented `_load_zep_config()` returning empty `GxConfig`
Loading 'datasources' ->
{}
Loaded 'datasources' ->
{}
warning: /Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/jinja2/environment.py:1088: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
warning:   return concat(self.root_render_func(self.new_context(vars)))
	1 expectation(s) included in expectation_suite.
Calculating Metrics: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 436.77it/s]
error: An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
error:                 TypeError: "expected string or bytes-like object".  Traceback: "Traceback (most recent call last):
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/great_expectations/render/renderer/site_builder.py", line 484, in build
error:     viewable_content = self.view_class.render(
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/great_expectations/render/view/view.py", line 110, in render
error:     return t.render(document, **kwargs)
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
error:     self.environment.handle_exception()
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
error:     reraise(*rewrite_traceback_stack(source=source))
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
error:     raise value.with_traceback(tb)
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/great_expectations/render/view/templates/page.j2", line 54, in top-level template code
error:     {% include 'section.j2' %}
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/great_expectations/render/view/templates/section.j2", line 6, in top-level template code
error:     {% include 'component.j2' %}
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/great_expectations/render/view/templates/component.j2", line 24, in top-level template code
error:     {{ content_block | render_content_block }}
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/great_expectations/render/view/view.py", line 199, in render_content_block
error:     return template.render(
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
error:     self.environment.handle_exception()
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
error:     reraise(*rewrite_traceback_stack(source=source))
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
error:     raise value.with_traceback(tb)
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/great_expectations/render/view/templates/table.j2", line 50, in top-level template code
error:     <td id="{{content_block_id}}" {{ cell_styling }}><div class="show-scrollbars">{{ cell | render_content_block(content_block_id=content_block_id + '-content') }}</div></td>
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/great_expectations/render/view/view.py", line 168, in render_content_block
error:     rendered_block += self.render_content_block(
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/great_expectations/render/view/view.py", line 192, in render_content_block
error:     return template.render(
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
error:     self.environment.handle_exception()
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
error:     reraise(*rewrite_traceback_stack(source=source))
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
error:     raise value.with_traceback(tb)
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/great_expectations/render/view/templates/collapse.j2", line 52, in top-level template code
error:     {{ block | render_content_block(content_block_id=content_block_id) }}
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/great_expectations/render/view/view.py", line 192, in render_content_block
error:     return template.render(
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
error:     self.environment.handle_exception()
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
error:     reraise(*rewrite_traceback_stack(source=source))
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
error:     raise value.with_traceback(tb)
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/great_expectations/render/view/templates/string_template.j2", line 1, in top-level template code
error:     {{ content_block["string_template"] | render_string_template }}
error:   File "/Users/vchung/Desktop/data_curator/.venv/lib/python3.8/site-packages/great_expectations/render/view/view.py", line 328, in render_string_template
error:     template["template"] = re.sub(
error:   File "/Users/vchung/opt/miniconda3/envs/synapse/lib/python3.8/re.py", line 210, in sub
error:     return _compile(pattern, flags).sub(repl, string, count)
error: TypeError: expected string or bytes-like object
error: ".
error: Column Challenge Name has the duplicate value(s) {'Awesome Challenge'} in rows: [2, 3].
error: For the attribute 'Challenge Status', on row 3, 'coming soon' is not one of ['upcoming', 'closed', 'active'].
error: For the attribute 'Challenge Description', on row 4, '' is too short.
error: For the attribute 'Challenge Status', on row 4, '' is not one of ['upcoming', 'closed', 'active'].
[[[2, 3], 'Challenge Name', "Column Challenge Name has the duplicate value(s) {'Awesome Challenge'} in rows: [2, 3].", {'Awesome Challenge'}], [3, 'Challenge Status', "'coming soon' is not one of ['upcoming', 'closed', 'active']", 'coming soon'], [4, 'Challenge Description', "'' is too short", ''], [4, 'Challenge Status', "'' is not one of ['upcoming', 'closed', 'active']", '']]
```

(Ignoring the traceback from one of schematic's dependencies) We can see that the expected validation errors were caught 🎉.  Additionally, schematic offers the choice to not utilize [Great Expectations](https://great-expectations.readthedocs.io/en/latest/intro.html) rules, which will offer a cleaner output at the expense of not catching the `unique` validation rule:

```
$ schematic model -c test_config.yml validate -mp ~/Desktop/challenge_manifest.csv -dt Challenge -rr
Starting schematic...
The (model > input > location) argument with value '/Users/vchung/Desktop/challenge_component.jsonld' is being read from the config file.
The (model > input > file_type) argument with value 'local' is being read from the config file.
JSON schema successfully generated from schema.org schema!
JSON schema file log stored as /Users/vchung/Desktop/challenge_component.Challenge.schema.json
Great Expetations suite will not be utilized.
error: For the attribute 'Challenge Status', on row 3, 'coming soon' is not one of ['active', 'closed', 'upcoming'].
error: For the attribute 'Challenge Description', on row 4, '' is too short.
error: For the attribute 'Challenge Status', on row 4, '' is not one of ['active', 'closed', 'upcoming'].
[[3, 'Challenge Status', "'coming soon' is not one of ['active', 'closed', 'upcoming']", 'coming soon'], [4, 'Challenge Description', "'' is too short", ''], [4, 'Challenge Status', "'' is not one of ['active', 'closed', 'upcoming']", '']]
```

**Comment by vpchung** [comment]
### (Tentative) Next Steps

"integrate [schematic] as part of the stack, e.g. creates Nx tasks that download the data from the Google Sheet, validate them and populate a DB in MariaDB"
