### ISSUE TITLE
[Story] Dockerize web client with SSR

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1342]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a user, I want social media site to generate rich cards when I insert a link to OC in a post so that my post looks more appealing.

### Description

Server side rendering (SSR) is required to benefit from the SEO techniques I implemented in 2022. The app can be started with SSR with the task `serve-ssr`. The goal of this ticket is to explore how to dockerize the app to use SSR.

### Acceptance criteria

- The Angular app can be started with SSR and Docker.
- LinkedIn generates a rich card in posts.
- Twitter generates a rich card in posts.

Out of scope:

- JSON-LD metadata implementation is already there but will be reviewed in a separate ticket.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
See the following articles:

- [Angular SSR with Angular Universal and Deploy with Docker](https://dev.to/this-is-angular/angular-ssr-with-angular-universal-and-deploy-with-docker-13i)
  - [GH repo](https://github.com/pavankjadda/angular-ssr-docker) used in the article.
- https://stackoverflow.com/a/67565140
- [SO post about Angular Universal and Nginx ](https://stackoverflow.com/questions/73814559/angular-ssr-is-not-working-in-docker-nginx/73844599)

**Comment by tschaffter** [comment]
### Update 2023-03-27

Last week I fixed a bug and now the SSR mode works fine again when started locally (`nx serve-ssr openchallenges-app`). I found an article that describes how to dockerize Angular SSR apps so this task shouldn't be too difficult to complete.

**Comment by tschaffter** [comment]
## Update 2023-09-22

Back to it with new resources:

- https://khumomogorosi.medium.com/deploy-angular-universal-application-on-nginx-server-2dfe0f32408e

**Comment by tschaffter** [comment]
## Update 2023-09-25

- Express engine: https://github.com/angular/universal/tree/main/modules/express-engine
  - Provides a request service that could be useful

**Comment by tschaffter** [comment]
## Solution 2: Using `http-server` and a single container

This solution is described in [Containerization, Creation of CI/CD Pipeline, and Free Hosting for Angular Universal App on Azure](https://medium.com/@rajat.1883/dockerization-ci-cd-pipelining-and-free-hosting-for-angular-universal-app-on-azure-abe6677197e7)

`Dockerfile.ssr`:

```
FROM node:20.7.0

WORKDIR /app
COPY dist/apps/openchallenges/app/browser /app/

EXPOSE 4200

RUN npm install -g http-server

# CMD ["node", "main.js"]

# CMD [ "http-server", "-p", "4200", "browser" ]
```

I can load `localhost:4200` and even navigate to other pages. However, loading a different page directly, even `/home`, leads to a 404 error:

```console
$ docker run --rm -it  -p 4200:4200 openchallenges-
app-ssr:local bash
root@3fbceca48ad8:/app# ls
browser  server
root@3fbceca48ad8:/app# http-server -p 4200 browser
Starting up http-server, serving browser

http-server version: 14.1.1

http-server settings: 
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  http://127.0.0.1:4200
  http://172.18.0.2:4200
Hit CTRL-C to stop the server

[2023-09-26T00:03:59.837Z]  "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
(node:9) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
[2023-09-26T00:03:59.990Z]  "GET /runtime.e32cd49f02c52c51.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:00.417Z]  "GET /styles.faa43c0f0a4758a3.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:00.435Z]  "GET /main.7e1b0b11e3a17e80.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:00.450Z]  "GET /polyfills.26f99692c01b8721.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:02.163Z]  "GET /config/config.json" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:02.254Z]  "GET /favicon.ico" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:02.386Z]  "GET /openchallenges-assets/images/openchallenges-color.svg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:02.388Z]  "GET /openchallenges-assets/images/graphic-search.svg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:02.389Z]  "GET /openchallenges-assets/images/graphic-challenges.svg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:02.810Z]  "GET /openchallenges-assets/images/graphic-hosts.svg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:17.498Z]  "GET /home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:17.500Z]  "GET /home" Error (404): "Not found"
[2023-09-26T00:04:32.236Z]  "GET /home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:32.237Z]  "GET /home" Error (404): "Not found"
[2023-09-26T00:04:34.225Z]  "GET /home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:34.226Z]  "GET /home" Error (404): "Not found"
[2023-09-26T00:04:34.470Z]  "GET /favicon.ico" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:38.149Z]  "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:38.298Z]  "GET /runtime.e32cd49f02c52c51.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:38.632Z]  "GET /polyfills.26f99692c01b8721.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:38.711Z]  "GET /main.7e1b0b11e3a17e80.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:38.768Z]  "GET /styles.faa43c0f0a4758a3.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:40.156Z]  "GET /config/config.json" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:40.356Z]  "GET /favicon.ico" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:40.439Z]  "GET /openchallenges-assets/images/graphic-search.svg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:40.440Z]  "GET /openchallenges-assets/images/openchallenges-color.svg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:40.793Z]  "GET /openchallenges-assets/images/graphic-challenges.svg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:40.904Z]  "GET /openchallenges-assets/images/graphic-hosts.svg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:50.909Z]  "GET /484.c9c7ed36a1b0f11c.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:51.014Z]  "GET /166.2c46931a7c652cac.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:51.047Z]  "GET /993.a237ed861e00b6c5.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:51.434Z]  "GET /primeicons.ba3f916dfb64be8c.woff2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:56.235Z]  "GET /common.26b533c01a318e73.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:04:56.574Z]  "GET /868.e700f35d83234c75.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:05:14.580Z]  "GET /home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:05:14.581Z]  "GET /home" Error (404): "Not found"
[2023-09-26T00:05:14.793Z]  "GET /favicon.ico" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:05:46.448Z]  "GET /home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
[2023-09-26T00:05:46.449Z]  "GET /home" Error (404): "Not found"
[2023-09-26T00:05:46.673Z]  "GET /favicon.ico" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"
```

**Comment by tschaffter** [comment]
## Solution 1: Serving SPA with Node

The solution is described in this [blog post](https://www.arunyadav.in/codehacks/blogs/post/25/part3-angular-universal-deployment).

Dockerfile:

```dockerfile
FROM node:20.7.0

WORKDIR /app
COPY dist/apps/openchallenges/app/browser/server /app/
COPY dist/apps/openchallenges/app/browser/browser /app/dist/apps/openchallenges/app/browser/browser

EXPOSE 4200

CMD ["node", "main.js"]
```

**Comment by tschaffter** [comment]
## Error: Failed to lookup view "index" in views directory

New error when running `nx serve-ssr openchallenges-app`

```console
Error: Failed to lookup view "index" in views directory "/workspaces/sage-monorepo/dist/apps/openchallenges/app/browser/browser"
    at render (./node_modules/express/lib/application.js:597:17)
    at ServerResponse.render (./node_modules/express/lib/response.js:1039:7)
    at <anonymous> (./apps/openchallenges/app/server.ts:47:9)
    at handle_request (./node_modules/express/lib/router/layer.js:95:5)
    at next (./node_modules/express/lib/router/route.js:144:13)
    at fn (./node_modules/express/lib/router/route.js:114:3)
    at handle_request (./node_modules/express/lib/router/layer.js:95:5)
    at done (./node_modules/express/lib/router/index.js:284:15)
    at param (./node_modules/express/lib/router/index.js:365:14)
    at param (./node_modules/express/lib/router/index.js:376:14)
```

**Comment by tschaffter** [comment]
## Issue: the production SSR server only returns the source of the home page

A flickering is also visible when reloading an org profile page, for instance. The home page would briefly show before showing the org profile page.

Once on the org profile page, opening the source of the page will show the source of the home page.

This issue does not affect the development server started with `nx serve-ssr openchallenges-app`.
