### ISSUE TITLE
[Bug] Certs error when building the image of the devcontainer

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Building the devcontainer image generates the following error:

```console
$ cd tools/devcontainers/sage/.devcontainer
$ docker build -t plop .

...
#5 76.57 Setting up ca-certificates-java (20190909) ...
#5 76.59 head: cannot open '/etc/ssl/certs/java/cacerts' for reading: No such file or directory
#5 76.66 Exception in thread "main" java.lang.InternalError: Error loading java.security file
#5 76.66        at java.base/java.security.Security.initialize(Security.java:106)
#5 76.66        at java.base/java.security.Security$1.run(Security.java:84)
#5 76.66        at java.base/java.security.Security$1.run(Security.java:82)
#5 76.66        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
#5 76.66        at java.base/java.security.Security.<clinit>(Security.java:82)
#5 76.66        at java.base/sun.security.jca.ProviderList.<init>(ProviderList.java:178)
#5 76.66        at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:96)
#5 76.66        at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:94)
#5 76.66        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
#5 76.66        at java.base/sun.security.jca.ProviderList.fromSecurityProperties(ProviderList.java:93)
#5 76.66        at java.base/sun.security.jca.Providers.<clinit>(Providers.java:55)
#5 76.66        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:156)
#5 76.66        at java.base/java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:193)
#5 76.66        at org.debian.security.KeyStoreHandler.<init>(KeyStoreHandler.java:50)
#5 76.66        at org.debian.security.UpdateCertificates.<init>(UpdateCertificates.java:65)
#5 76.66        at org.debian.security.UpdateCertificates.main(UpdateCertificates.java:51)
#5 76.67 dpkg: error processing package ca-certificates-java (--configure):
#5 76.67  installed ca-certificates-java package post-installation script subprocess returned error exit status 1
#5 76.67 dpkg: dependency problems prevent configuration of openjdk-17-jre-headless:amd64:
#5 76.67  openjdk-17-jre-headless:amd64 depends on ca-certificates-java (>= 20190405~); however:
#5 76.67   Package ca-certificates-java is not configured yet.
#5 76.67 
#5 76.67 dpkg: error processing package openjdk-17-jre-headless:amd64 (--configure):
#5 76.67  dependency problems - leaving unconfigured
#5 76.67 dpkg: dependency problems prevent configuration of openjdk-17-jre:amd64:
#5 76.67  openjdk-17-jre:amd64 depends on openjdk-17-jre-headless (= 17.0.7+7-1~deb11u1); however:
#5 76.67   Package openjdk-17-jre-headless:amd64 is not configured yet.
#5 76.67 
#5 76.67 dpkg: error processing package openjdk-17-jre:amd64 (--configure):
#5 76.67  dependency problems - leaving unconfigured
#5 76.67 dpkg: dependency problems prevent configuration of openjdk-17-jdk:amd64:
#5 76.67  openjdk-17-jdk:amd64 depends on openjdk-17-jre (= 17.0.7+7-1~deb11u1); however:
#5 76.67   Package openjdk-17-jre:amd64 is not configured yet.
#5 76.67 
#5 76.67 dpkg: error processing package openjdk-17-jdk:amd64 (--configure):
#5 76.67  dependency problems - leaving unconfigured
#5 76.67 dpkg: dependency problems prevent configuration of openjdk-17-jdk-headless:amd64:
#5 76.67  openjdk-17-jdk-headless:amd64 depends on openjdk-17-jre-headless (= 17.0.7+7-1~deb11u1); however:
#5 76.67   Package openjdk-17-jre-headless:amd64 is not configured yet.
#5 76.67 
#5 76.67 dpkg: error processing package openjdk-17-jdk-headless:amd64 (--configure):
#5 76.67  dependency problems - leaving unconfigured
#5 76.67 Processing triggers for libc-bin (2.31-13+deb11u4) ...
#5 76.69 Processing triggers for ca-certificates (20210119) ...
#5 76.70 Updating certificates in /etc/ssl/certs...
#5 77.09 0 added, 0 removed; done.
#5 77.09 Running hooks in /etc/ca-certificates/update.d...
#5 77.10 
#5 77.14 /etc/ca-certificates/update.d/jks-keystore: 82: java: not found
#5 77.14 E: /etc/ca-certificates/update.d/jks-keystore exited with code 1.
#5 77.14 done.
#5 77.16 Errors were encountered while processing:
#5 77.16  ca-certificates-java
#5 77.16  openjdk-17-jre-headless:amd64
#5 77.16  openjdk-17-jre:amd64
#5 77.16  openjdk-17-jdk:amd64
#5 77.16  openjdk-17-jdk-headless:amd64
#5 77.23 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
executor failed running [/bin/bash -euxo pipefail -c groupadd docker   && apt-get update -qq -y && export DEBIAN_FRONTEND=noninteractive   && apt-get install --no-install-recommends -qq -y     ca-certificates curl git bash-completion gnupg2 lsb-release ssh sudo     python3-pip python3-dev python-is-python3 openjdk-17-jdk     htop unzip vim wget lsof iproute2 build-essential     kafkacat jq     mandoc     locales     make build-essential libssl-dev zlib1g-dev libbz2-dev     libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev     xz-utils tk-dev libffi-dev liblzma-dev   && curl -sL https://deb.nodesource.com/setup_18.x | bash -   && curl -sSL https://cli.github.com/packages/githubcli-archive-keyring.gpg |       gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg   && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" |       tee /etc/apt/sources.list.d/github-cli.list > /dev/null   && curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null   && echo "deb https://ngrok-agent.s3.amazonaws.com bullseye main" | tee /etc/apt/sources.list.d/ngrok.list   && curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -   && echo "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list   && apt-get update -qq -y   && apt-get install --no-install-recommends -qq -y     nodejs gh ngrok     terraform=1.4.6-1     vault=1.13.2-1   && setcap -r /usr/bin/vault   && corepack enable yarn   && corepack prepare "yarn@${yarnVersion}" --activate   && npm install -g "@devcontainers/cli@${devcontainerCliVersion}"   && curl "https://raw.githubusercontent.com/nektos/act/v${actVersion}/install.sh" | bash -   && curl -sSL "https://github.com/sharkdp/hyperfine/releases/download/v${hyperfineVersion}/hyperfine_${hyperfineVersion}_amd64.deb"     -o /tmp/hyperfine.deb   && apt-get install --no-install-recommends -qq -y /tmp/hyperfine.deb   && rm -fr /tmp/hyperfine.deb   && curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip   && unzip awscliv2.zip   && ./aws/install   && rm -fr awscliv2.zip ./aws   && curl -fsSL "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o /tmp/session-manager-plugin.deb   && dpkg -i /tmp/session-manager-plugin.deb   && rm -fr /tmp/session-manager-plugin.deb   && curl -sSL https://install.python-poetry.org | POETRY_HOME=/etc/poetry python3 - --version "${poetryVersion}"   && ln -s /etc/poetry/bin/poetry /usr/local/bin/.   && echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf   && apt-get -y autoclean   && apt-get -y autoremove   && rm -rf /var/lib/apt/lists/*   && pip install --no-cache-dir pipenv]: exit code: 100
```

### Expected behavior

The image should build without issue. I didn't change anything since we built and published the latest devcontainer image. An external component should have changed since then, e.g. an system package.

### Commit ID

591f01c

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
Installing the package `ca-certificates-java` solved the issue as suggested [here](https://stackoverflow.com/a/76274209).
