### ISSUE TITLE
[Bug] ES says `primary shard is not active`

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

Failing to start Elasticsearch in the Ubuntu 22.04 devcontainer that I'm testing.

```console
{"type": "server", "timestamp": "2023-07-25T19:39:21,859Z", "level": "ERROR", "component": "o.e.i.g.GeoIpDownloader", "cluster.name": "openchallenges-elasticsearch", "node.name": "openchallenges-elasticsearch-node-3", "message": "error updating geoip database [GeoLite2-City.mmdb]", "cluster.uuid": "SCCN-RDLS0uLTlVRHkpHow", "node.id": "50tsAzjaRkalnTq0FfsJ6w" , 
"stacktrace": ["org.elasticsearch.action.UnavailableShardsException: [.geoip_databases][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[.geoip_databases][0]] containing [index {[.geoip_databases][_doc][GeoLite2-City.mmdb_0_1690313901762], source[n/a, actual length: [1mb], max length: 2kb]}]]",
"at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.retryBecauseUnavailable(TransportReplicationAction.java:1077) ~[elasticsearch-7.17.8.jar:7.17.8]",
"at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:873) ~[elasticsearch-7.17.8.jar:7.17.8]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.8.jar:7.17.8]",
"at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$2.onTimeout(TransportReplicationAction.java:1032) ~[elasticsearch-7.17.8.jar:7.17.8]",
"at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:345) ~[elasticsearch-7.17.8.jar:7.17.8]",
"at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:263) ~[elasticsearch-7.17.8.jar:7.17.8]",
"at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:660) ~[elasticsearch-7.17.8.jar:7.17.8]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718) ~[elasticsearch-7.17.8.jar:7.17.8]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]",
"at java.lang.Thread.run(Thread.java:1589) [?:?]"] }
```

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
This error occurred when I was inside the devcontainer with `docker-outside-of-docker`, this is not the standard way to run the stack. The issue didn't appear when returning to `docker-in-docker.`
