### ISSUE TITLE
[Story] Minimize the time it takes to initialize the dev container during CI

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1975]
## Background

The CI workflow has recently been updated to use the Dev Container CLI to run tasks in the dev container. This ensures that the environment used by the CI workflow is the same as the development environment used by developers. This container also provides all the tools needed by the CI workflow and eliminates the need to maintain different versions of the tools in the CI workflow.

One drawback of the current implementation is that the dev container is not caching dependencies for Python, Java, Node.js, etc. This means that dependencies needs to be downloaded again from remote servers each time the CI workflow runs.

Initializing the dev container in the CI workflow is composed of two steps: 1) start the dev container and 2) run the command `workspace-install`. These two takes can take together up to 6 minutes.

## Goal

The goal of this ticket is to explore means to minimize the initialization of the dev container. The tasks are:

- [x] #1979
- [x] #1982 
- [x] #1983 
- [x] #1988 
- [x] #1852

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
## Time it takes to start the dev container

This workflow step takes slightly less than 2 minutes based on the runtime of past runs.

The Dev Container CLI performs the following operations:

1. Download the base image of the dev container
2. Build a new image: base image + install features + VS Code extensions + configuration defined in `devcontainer.json`

Option to reduce the start up time:

- Cache Docker images so that the base image is cached
- Remove dev container features and VS Code extension that are not used by the CI workflow
- Go back to running the base dev container without the Docker CLI
  - One issue that prevented this is that the Docker CLI was not installed in the dev container

**Comment by tschaffter** [comment]
## About stopping the dev container

This step takes 4 seconds, which is not much. It's also probably safer to shutdown the container properly.

**Comment by tschaffter** [comment]
## GH Runner hardware resources

- CPU cores: 2
- RAM: 7 GB
- Storage:
    ```console
    Run df -h
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/root        84G   62G   22G  75% /
    tmpfs           3.4G  172K  3.4G   1% /dev/shm
    tmpfs           1.4G  1.1M  1.4G   1% /run
    tmpfs           5.0M     0  5.0M   0% /run/lock
    /dev/sda15      105M  6.1M   99M   6% /boot/efi
    /dev/sdb1        14G  4.1G  9.0G  31% /mnt
    tmpfs           694M   12K  694M   1% /run/user/1001
    ```

The CPU and RAM information matches the following GH runner, though we seem to have access to more storage.

- 2-core CPU (x86_64)
- 7 GB of RAM
- 14 GB of SSD space

Source: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

**Comment by tschaffter** [comment]
## About downloading the base dev container image

- Without caching Docker images on the runner, it takes 58.1s to pull the base image.
- When caching Docker images on the runner, it takes the same amount of time to pull the base image.

Questions:
- Is the image cached when using the dev container CLI?
- Is the dev container CLI using the cache?
- Did I run the workflow too soon after expecting the image to have been previously cached?

**Comment by tschaffter** [comment]
## About installing VS Code extension

I thought that the dev container CLI was installing the VS Code extensions specified in `devcontainer.json` when running `devcontainer up`. However, there is nothing in the logs that shows that extensions are installed. Remove the extensions from the definition file also does not seem to speed up `devcontainer up`.

**Comment by tschaffter** [comment]
## Docker images are not cached

Cache Docker layers says:

```console
Run actions/cache@v3
  with:
    path: /tmp/.buildx-cache
    key: Linux-single-buildx-82425368edcaf7acea638514ddd0cdc3809229bd
    restore-keys: Linux-single-buildx
  
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false
  env:
    NX_BRANCH: 1976
    NX_RUN_GROUP: 5881219943
    NX_CLOUD_AUTH_TOKEN: 
    NX_CLOUD_ENCRYPTION_KEY: 
    NX_CLOUD_ENV_NAME: linux
    NX_BASE: df9fdd5b6b76b1a367103020ac738406a403c7e3
    NX_HEAD: d6b57f4dbbc84b5e77489f011e9527fb717a329e
Cache not found for input keys: Linux-single-buildx-82425368edcaf7acea638514ddd0cdc3809229bd, Linux-single-buildx
```

Post Cache Docker Layers says:

> Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.

**Comment by tschaffter** [comment]
## Still need to find where image layer are store

```console
devcontainer up --cache-from /tmp/.buildx-cache --workspace-folder ../sage-monorepo
```

does not save data to `/tmp/.buildx-cache` even if the folder is created beforehand.

**Comment by tschaffter** [comment]
We need the new option `--cache-to` recently added: https://github.com/devcontainers/cli/pull/570

**Comment by tschaffter** [comment]
## What I learned from #1978

This was an attempt to make the GH runner run the entire job in the container with:

```yaml
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sage-bionetworks/sage-devcontainer:55645b0
      options: --user root
```

By default, GH runners are run as `root`. On the other hand, Sage Monorepo environment has been designed to be executed by a non-root user (`vscode`). Trying to run the container as non-root (`--user vscode`) results in the checkout job failing:

```console
node:internal/fs/utils:345
    throw err;
    ^

Error: EACCES: permission denied, open '/__w/_temp/_runner_file_commands/save_state_feaa9342-be15-443b-927e-e3115f27f843'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2170:35)
    at Object.appendFileSync (node:fs:2232:6)
    at Object.issueFileCommand (/__w/_actions/actions/checkout/v3/dist/index.js:2945:8)
    at Object.saveState (/__w/_actions/actions/checkout/v3/dist/index.js:2862:31)
    at Object.8647 (/__w/_actions/actions/checkout/v3/dist/index.js:2321:10)
    at __nccwpck_require__ (/__w/_actions/actions/checkout/v3/dist/index.js:18251:43)
    at Object.2565 (/__w/_actions/actions/checkout/v3/dist/index.js:146:34)
    at __nccwpck_require__ (/__w/_actions/actions/checkout/v3/dist/index.js:18251:43)
    at Object.9210 (/__w/_actions/actions/checkout/v3/dist/index.js:1141:36) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/__w/_temp/_runner_file_commands/save_state_feaa9342-be15-443b-927e-e3115f27f843'
}
```

See this thread: https://github.com/actions/checkout/issues/1014

The id of the user and the permission of the folder mounted by the runner that leads the checkout step to fails. This issue is summarized [here](https://github.com/actions/runner/issues/2278#issuecomment-1333516721).

```console
    steps:
      - name: Check id
        run: |
          id
          sudo ls -al /__w/_temp/

Run id
uid=1000(vscode) gid=1001(vscode) groups=1001(vscode),27(sudo),1000(docker)
total 24
drwxr-xr-x 5 1001  123 4096 Aug 17 03:55 .
drwxr-xr-x 6 1001 root 4096 Aug 17 03:54 ..
-rw-r--r-- 1 1001  123   27 Aug 17 03:55 27042907-d87a-4624-9b13-597a25316578.sh
drwxr-xr-x 2 1001  123 4096 Aug 17 03:55 _github_home
drwxr-xr-x 2 1001  123 4096 Aug 17 03:55 _github_workflow
drwxr-xr-x 2 1001  123 4096 Aug 17 03:55 _runner_file_commands
```

**Comment by tschaffter** [comment]
## Cache when workflow run for PR vs push to `main`

The caches created by `actions/cache@v3` when running the CI workflow in a PR is not available to `main`.

I observed this as the workflow running for `main` had the same cache key for Poetry as the key used when running the workflow for a PR, however the cache could not be found for `main`. I rerun the workflow on `main` and that time the cache was available. The cache was created during the first run on `main`.

**Comment by tschaffter** [comment]
Added to Sprint 23.10
