### ISSUE TITLE
[Bug] OC Apex is returning `Internal Server Error`

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

Accessing `localhost:8000` shows the error "Internal Server Error". The console shows:

```console
GET
http://localhost:8000/
[HTTP/1.1 500 Internal Server Error 109ms]

Content-Security-Policy: The page’s settings blocked the loading of a resource at http://localhost:8000/favicon.ico (“default-src”).
```

The issue is likely because of the new image for the SSR app.

The app can still be successfully access on `localhost:8000`.

### Commit ID

9bdd016252b2bb889421d263a7de52f0212494a3

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
The container of the app is throwing the following error(s). This issue is likely related to the new image for SSR and/or the last PR I merged about Google Tab Manager (I use `length` there).

```console
$ docker logs -f openchallenges-app
Node Express server listening on http://localhost:4200
Unable to load the config file:  HttpErrorResponse {
  headers: HttpHeaders {
    normalizedNames: Map(0) {},
    lazyUpdate: null,
    headers: Map(0) {}
  },
  status: 0,
  statusText: 'Unknown Error',
  url: 'http://localhost:8000/config/config.json',
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure response for http://localhost:8000/config/config.json: 0 Unknown Error',
  error: ProgressEvent2 {
    type: 'error',
    target: XMLHttpRequest2 {
      onloadstart: null,
      onprogress: null,
      onabort: null,
      onerror: null,
      onload: null,
      ontimeout: null,
      onloadend: null,
      _listeners: [Object],
      onreadystatechange: null,
      _anonymous: undefined,
      readyState: 4,
      response: null,
      responseText: '',
      responseType: 'text',
      responseURL: '',
      status: 0,
      statusText: '',
      timeout: 0,
      upload: [XMLHttpRequestUpload],
      _method: 'GET',
      _url: [Url],
      _sync: false,
      _headers: [Object],
      _loweredHeaders: [Object],
      _mimeOverride: null,
      _request: null,
      _response: null,
      _responseParts: null,
      _responseHeaders: null,
      _aborting: null,
      _error: null,
      _loadedBytes: 0,
      _totalBytes: 0,
      _lengthComputable: false
    },
    currentTarget: XMLHttpRequest2 {
      onloadstart: null,
      onprogress: null,
      onabort: null,
      onerror: null,
      onload: null,
      ontimeout: null,
      onloadend: null,
      _listeners: [Object],
      onreadystatechange: null,
      _anonymous: undefined,
      readyState: 4,
      response: null,
      responseText: '',
      responseType: 'text',
      responseURL: '',
      status: 0,
      statusText: '',
      timeout: 0,
      upload: [XMLHttpRequestUpload],
      _method: 'GET',
      _url: [Url],
      _sync: false,
      _headers: [Object],
      _loweredHeaders: [Object],
      _mimeOverride: null,
      _request: null,
      _response: null,
      _responseParts: null,
      _responseHeaders: null,
      _aborting: null,
      _error: null,
      _loadedBytes: 0,
      _totalBytes: 0,
      _lengthComputable: false
    },
    lengthComputable: false,
    loaded: 0,
    total: 0
  }
}
ERROR TypeError: Cannot read properties of undefined (reading 'length')
    at new AppComponent2 (/app/main.js:1:3862620)
    at AppComponent2.ɵfac [as factory] (/app/main.js:1:3862991)
    at getNodeInjectable (/app/main.js:1:1496598)
    at createRootComponent (/app/main.js:1:1584982)
    at ComponentFactory.create (/app/main.js:1:1585491)
    at ApplicationRef3.bootstrap (/app/main.js:1:1695814)
    at /app/main.js:1:1689757
    at _ZoneDelegate2.invoke (/app/main.js:1:1286469)
    at Object.onInvoke (/app/main.js:1:1680174)
    at _ZoneDelegate2.invoke (/app/main.js:1:1286365)
TypeError: Cannot read properties of undefined (reading 'length')
    at new AppComponent2 (/app/main.js:1:3862620)
    at AppComponent2.ɵfac [as factory] (/app/main.js:1:3862991)
    at getNodeInjectable (/app/main.js:1:1496598)
    at createRootComponent (/app/main.js:1:1584982)
    at ComponentFactory.create (/app/main.js:1:1585491)
    at ApplicationRef3.bootstrap (/app/main.js:1:1695814)
    at /app/main.js:1:1689757
    at _ZoneDelegate2.invoke (/app/main.js:1:1286469)
    at Object.onInvoke (/app/main.js:1:1680174)
    at _ZoneDelegate2.invoke (/app/main.js:1:1286365)
```

**Comment by tschaffter** [comment]
From the browser:

- `http://localhost:4200/config/config.json` works
- `http://localhost:8000/config/config.json` works too!

But the app says that it cannot find it because `localhost` is a special domain... This issue would not arise in production, e.g. where the host name inferred in `server.ts` is `openchallenges.io`.

**Comment by tschaffter** [comment]
## Using `./` to load the config file

- It works with CSR
- It does not work with SSR:

```console
Compiled successfully.
base URL: http://localhost:39801
is server platform: true
Unable to load the config file:  NetworkError
    at send (./node_modules/xhr2/lib/xhr2.js:281:19)
    at observer (./node_modules/@angular/common/fesm2022/http.mjs:2190:21)
    at _trySubscribe (./node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
    at cb (./node_modules/rxjs/dist/cjs/internal/Observable.js:35:31)
    at errorContext (./node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at subscribe (./node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)
    at onNext (./node_modules/rxjs/dist/cjs/internal/operators/switchMap.js:17:63)
    at _next (./node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at next (./node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at <anonymous> (./node_modules/rxjs/dist/cjs/internal/observable/innerFrom.js:120:28)
```
