### ISSUE TITLE
[Bug] Prettier says `SyntaxError: Only void and foreign elements can be self closed "openchallenges-challenge-search" (15:3)`

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

```console
["INFO" - 10:07:52 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 10:07:52 PM] Prettier Options:
{
  "filepath": "/workspaces/sage-monorepo/libs/openchallenges/home/src/lib/home.component.html",
  "parser": "angular",
  "useTabs": false,
  "tabWidth": 2,
  "singleQuote": true,
  "printWidth": 100,
  "xmlWhitespaceSensitivity": "ignore"
}
["ERROR" - 10:07:52 PM] Error formatting document.
["ERROR" - 10:07:52 PM] Only void and foreign elements can be self closed "openchallenges-challenge-search" (15:3)
  13 |     </h4>
  14 |   </div>
> 15 |   <openchallenges-challenge-search />
     |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  16 |   <openchallenges-statistics-viewer *sageAppShellNoRender/>
  17 |   <openchallenges-random-challenge-list *sageAppShellNoRender/>
  18 |   <openchallenges-challenge-registration *sageAppShellNoRender/>
SyntaxError: Only void and foreign elements can be self closed "openchallenges-challenge-search" (15:3)
  13 |     </h4>
  14 |   </div>
> 15 |   <openchallenges-challenge-search />
     |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  16 |   <openchallenges-statistics-viewer *sageAppShellNoRender/>
  17 |   <openchallenges-random-challenge-list *sageAppShellNoRender/>
  18 |   <openchallenges-challenge-registration *sageAppShellNoRender/>
	at t (/workspaces/sage-monorepo/node_modules/prettier/parser-html.js:4:2359)
	at al (/workspaces/sage-monorepo/node_modules/prettier/parser-html.js:36:6425)
	at Ts (/workspaces/sage-monorepo/node_modules/prettier/parser-html.js:36:7938)
	at Object.parse (/workspaces/sage-monorepo/node_modules/prettier/parser-html.js:36:8710)
	at Object.parse (/workspaces/sage-monorepo/node_modules/prettier/index.js:7334:23)
	at coreFormat (/workspaces/sage-monorepo/node_modules/prettier/index.js:8645:18)
	at formatWithCursor2 (/workspaces/sage-monorepo/node_modules/prettier/index.js:8837:18)
	at /workspaces/sage-monorepo/node_modules/prettier/index.js:37229:12
	at Object.format (/workspaces/sage-monorepo/node_modules/prettier/index.js:37243:12)
	at t.PrettierMainThreadInstance.format (/home/vscode/.vscode-server/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:17961)
	at t.default.format (/home/vscode/.vscode-server/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:16052)
	at async t.PrettierEditProvider.provideEdits (/home/vscode/.vscode-server/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:12610)
	at async M.provideDocumentFormattingEdits (/vscode/vscode-server/bin/linux-x64/fdb98833154679dbaa7af67a5a29fe19e55c2b73/out/vs/workbench/api/node/extensionHostProcess.js:110:45916)
["INFO" - 10:07:52 PM] Formatting completed in 32ms.
```

### Commit ID

45b5a7d3c010b7f0e5dc2e6824a88880ffe1d012

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
According to this [post](https://stackoverflow.com/a/75249429), the solution may be to update prettier to version 2.8.3. We are currently using 2.7.1.
