### ISSUE TITLE
[Bug] Language support for Java does not start properly

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

The Language server for Java in VS Code fails to start. This results in Intellisense not being available to Java files.

Language server logs:

```console
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
Nov 07, 2023 8:26:11 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic
Nov 07, 2023 8:26:11 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic
Nov 07, 2023 8:26:24 PM com.microsoft.java.debug.plugin.internal.JavaDebuggerServerPlugin start
INFO: Starting com.microsoft.java.debug.plugin
[Error - 8:26:54 PM] Nov 7, 2023, 8:26:54 PM Unable to load IDecompiler class for jarFileContentProvider
Nov 07, 2023 8:32:51 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 190
```

### Commit ID

4addaa2ad44084f6b69ee6628d2f0efeca621005

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
I should actually look at the log of the `Language support for Java (Syntax Server)`. For a file of the challenge service:

```console
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
[Error - 8:44:09 PM] Nov 7, 2023, 8:44:09 PM [Working copy] ChallengeServiceApplication.java [in org.sagebionetworks.openchallenges.challenge.service [in src [in jdt.ls-java-project]]] does not exist
[Working copy] ChallengeServiceApplication.java [in org.sagebionetworks.openchallenges.challenge.service [in src [in jdt.ls-java-project]]] does not exist
Java Model Exception: Error in Java Model (code 969): [Working copy] ChallengeServiceApplication.java [in org.sagebionetworks.openchallenges.challenge.service [in src [in jdt.ls-java-project]]] does not exist
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:550)
	at org.eclipse.jdt.internal.core.Openable.getUnderlyingResource(Openable.java:358)
	at org.eclipse.jdt.internal.core.CompilationUnit.getUnderlyingResource(CompilationUnit.java:986)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDiagnosticsHandler.collectNonJavaProblems(BaseDiagnosticsHandler.java:149)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDiagnosticsHandler.endReporting(BaseDiagnosticsHandler.java:135)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.reportProblems(ReconcileWorkingCopyOperation.java:148)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:112)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:806)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1325)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler.publishDiagnostics(BaseDocumentLifeCycleHandler.java:325)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler.publishDiagnostics(BaseDocumentLifeCycleHandler.java:288)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler$PublishDiagnosticJob.run(BaseDocumentLifeCycleHandler.java:734)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by tschaffter** [comment]
## `ImageServiceApplication.java is a non-project file, only syntax errors are reportedJava(16)`

> I got the same warning simply because I had two Java (Maven) projects in the same Visual Studio Code workspace.

[Source](https://stackoverflow.com/a/63188536)

That may be why.

> In VS Code, run "Java: Clean the Java language server workspace"

This did not work.

**Comment by tschaffter** [comment]
This has no longer been an issue recently.
