### ISSUE TITLE
[Bug] Unable to run `iatlas-data:serve-detach`

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

iAtlas

### Current behavior

The project iatlas-data was added in the #2411. At the time, I was able to successfully run the containerized application with the command shown below and in the Preview section of the PR.

```
nx serve-detach iatlas-data
```

I'm trying to run the same command today and it fails with the following error:

```
$ docker logs iatlas-data
Traceback (most recent call last):
  File "/src/build_database.py", line 1598, in <module>
    schema = Schema(
  File "/usr/local/lib/python3.10/site-packages/schematic_db/schema/schema.py", line 146, in __init__
    self.schema_graph = SchemaGraph(config.schema_url)
  File "/usr/local/lib/python3.10/site-packages/schematic_db/schema_graph/schema_graph.py", line 18, in __init__
    self.schema_graph = self.create_schema_graph()
  File "/usr/local/lib/python3.10/site-packages/schematic_db/schema_graph/schema_graph.py", line 26, in create_schema_graph
    subgraph = get_graph_by_edge_type(self.schema_url, "requiresComponent")
  File "/usr/local/lib/python3.10/site-packages/schematic_db/api_utils/api_utils.py", line 185, in get_graph_by_edge_type
    response = create_schematic_api_response("schemas/get/graph_by_edge_type", params)
  File "/usr/local/lib/python3.10/site-packages/schematic_db/api_utils/api_utils.py", line 121, in create_schematic_api_response
    raise SchematicAPIError(
schematic_db.api_utils.api_utils.SchematicAPIError: Error accessing Schematic endpoint; URL: https://schematic-staging.api.sagebionetworks.org/v1/schemas/get/graph_by_edge_type; Code: 500; Reason: INTERNAL SERVER ERROR; Time (PST): 2024-03-11 10:40:49.355164-07:00; Parameters: {'schema_url': 'https://raw.githubusercontent.com/CRI-iAtlas/iAtlasSchema/main/iatlas_schema.jsonld', 'relationship': 'requiresComponent'}
```

### Expected behavior

The command should complete successfully.

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrewelamb** [comment]
Definitely possible! It woudl just take some effort to create the mock data, or change schematic db to be able to take in a subset of the manifests.
