### ISSUE TITLE
Fix Can't bind to 'countUp' since it isn't a known property of 'h2' (ngx-typed-js library)

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#554]
The unit test of the project `challenge-registry-home` are broken in `main`.

```console
vscode@d830a43b283a:/workspaces/challenge-registry$ nx test challenge-registry-home

> nx run challenge-registry-home:test  [existing outputs match the cache, left as is]

 PASS   web-home  libs/challenge-registry/home/src/lib/challenge-host-list/challenge-host-list.component.spec.ts
 PASS   web-home  libs/challenge-registry/home/src/lib/challenge-registration/challenge-registration.component.spec.ts
 PASS   web-home  libs/challenge-registry/home/src/lib/topics-viewer/topics-viewer.component.spec.ts
 PASS   web-home  libs/challenge-registry/home/src/lib/featured-challenge-list/featured-challenge-list.component.spec.ts
 PASS   web-home  libs/challenge-registry/home/src/lib/statistics-viewer/statistics-viewer.component.spec.ts
  ● Console

    console.error
      NG0303: Can't bind to 'countUp' since it isn't a known property of 'h2' (used in the 'StatisticsViewerComponent' component template).
      1. If 'h2' is an Angular component and it has the 'countUp' input, then verify that it is a part of an @NgModule where this component is declared.
      2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

      at reportUnknownPropertyError (../../../node_modules/@angular/core/fesm2020/core.mjs:7506:17)
      at handleUnknownPropertyError (../../../node_modules/@angular/core/fesm2020/core.mjs:7499:5)
      at elementPropertyInternal (../../../node_modules/@angular/core/fesm2020/core.mjs:12520:17)
      at ɵɵproperty (../../../node_modules/@angular/core/fesm2020/core.mjs:15289:9)
      at StatisticsViewerComponent_Template (../../../ng:/StatisticsViewerComponent.js:33:9)
      at executeTemplate (../../../node_modules/@angular/core/fesm2020/core.mjs:12125:9)
      at refreshView (../../../node_modules/@angular/core/fesm2020/core.mjs:11988:13)
      at refreshComponent (../../../node_modules/@angular/core/fesm2020/core.mjs:13084:13)

    console.error
      NG0303: Can't bind to 'countUp' since it isn't a known property of 'h2' (used in the 'StatisticsViewerComponent' component template).
      1. If 'h2' is an Angular component and it has the 'countUp' input, then verify that it is a part of an @NgModule where this component is declared.
      2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

      at reportUnknownPropertyError (../../../node_modules/@angular/core/fesm2020/core.mjs:7506:17)
      at handleUnknownPropertyError (../../../node_modules/@angular/core/fesm2020/core.mjs:7499:5)
      at elementPropertyInternal (../../../node_modules/@angular/core/fesm2020/core.mjs:12520:17)
      at ɵɵproperty (../../../node_modules/@angular/core/fesm2020/core.mjs:15289:9)
      at StatisticsViewerComponent_Template (../../../ng:/StatisticsViewerComponent.js:35:9)
      at executeTemplate (../../../node_modules/@angular/core/fesm2020/core.mjs:12125:9)
      at refreshView (../../../node_modules/@angular/core/fesm2020/core.mjs:11988:13)
      at refreshComponent (../../../node_modules/@angular/core/fesm2020/core.mjs:13084:13)

    console.error
      NG0303: Can't bind to 'countUp' since it isn't a known property of 'h2' (used in the 'StatisticsViewerComponent' component template).
      1. If 'h2' is an Angular component and it has the 'countUp' input, then verify that it is a part of an @NgModule where this component is declared.
      2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

      at reportUnknownPropertyError (../../../node_modules/@angular/core/fesm2020/core.mjs:7506:17)
      at handleUnknownPropertyError (../../../node_modules/@angular/core/fesm2020/core.mjs:7499:5)
      at elementPropertyInternal (../../../node_modules/@angular/core/fesm2020/core.mjs:12520:17)
      at ɵɵproperty (../../../node_modules/@angular/core/fesm2020/core.mjs:15289:9)
      at StatisticsViewerComponent_Template (../../../ng:/StatisticsViewerComponent.js:37:9)
      at executeTemplate (../../../node_modules/@angular/core/fesm2020/core.mjs:12125:9)
      at refreshView (../../../node_modules/@angular/core/fesm2020/core.mjs:11988:13)
      at refreshComponent (../../../node_modules/@angular/core/fesm2020/core.mjs:13084:13)

 PASS   web-home  libs/challenge-registry/home/src/lib/sponsor-list/sponsor-list.component.spec.ts
 PASS   web-home  libs/challenge-registry/home/src/lib/challenge-search/challenge-search.component.spec.ts
  ● Console

    console.error
      NG0304: 'ngx-typed-js' is not a known element (used in the 'ChallengeSearchComponent' component template):
      1. If 'ngx-typed-js' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
      2. If 'ngx-typed-js' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

      at validateElementIsKnown (../../../node_modules/@angular/core/fesm2020/core.mjs:7413:25)
      at elementStartFirstCreatePass (../../../node_modules/@angular/core/fesm2020/core.mjs:15320:9)
      at ɵɵelementStart (../../../node_modules/@angular/core/fesm2020/core.mjs:15358:9)
      at ChallengeSearchComponent_ngx_typed_js_5_Template (../../../ng:/ChallengeSearchComponent.js:9:5)
      at executeTemplate (../../../node_modules/@angular/core/fesm2020/core.mjs:12125:9)
      at renderView (../../../node_modules/@angular/core/fesm2020/core.mjs:11925:13)
      at TemplateRef2.createEmbeddedView (../../../node_modules/@angular/core/fesm2020/core.mjs:23145:9)
      at ViewContainerRef2.createEmbeddedView (../../../node_modules/@angular/core/fesm2020/core.mjs:23263:37)

    console.error
      NG0303: Can't bind to 'strings' since it isn't a known property of 'ngx-typed-js' (used in the 'ChallengeSearchComponent' component template).
      1. If 'ngx-typed-js' is an Angular component and it has the 'strings' input, then verify that it is a part of an @NgModule where this component is declared.
      2. If 'ngx-typed-js' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
      3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

      at reportUnknownPropertyError (../../../node_modules/@angular/core/fesm2020/core.mjs:7506:17)
      at handleUnknownPropertyError (../../../node_modules/@angular/core/fesm2020/core.mjs:7499:5)
      at elementPropertyInternal (../../../node_modules/@angular/core/fesm2020/core.mjs:12520:17)
      at ɵɵproperty (../../../node_modules/@angular/core/fesm2020/core.mjs:15289:9)
      at ChallengeSearchComponent_ngx_typed_js_5_Template (../../../ng:/ChallengeSearchComponent.js:13:17)
      at executeTemplate (../../../node_modules/@angular/core/fesm2020/core.mjs:12125:9)
      at refreshView (../../../node_modules/@angular/core/fesm2020/core.mjs:11988:13)
      at refreshEmbeddedViews (../../../node_modules/@angular/core/fesm2020/core.mjs:13038:17)

    console.error
      NG0303: Can't bind to 'loop' since it isn't a known property of 'ngx-typed-js' (used in the 'ChallengeSearchComponent' component template).
      1. If 'ngx-typed-js' is an Angular component and it has the 'loop' input, then verify that it is a part of an @NgModule where this component is declared.
      2. If 'ngx-typed-js' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
      3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

      at reportUnknownPropertyError (../../../node_modules/@angular/core/fesm2020/core.mjs:7506:17)
      at handleUnknownPropertyError (../../../node_modules/@angular/core/fesm2020/core.mjs:7499:5)
      at elementPropertyInternal (../../../node_modules/@angular/core/fesm2020/core.mjs:12520:17)
      at ɵɵproperty (../../../node_modules/@angular/core/fesm2020/core.mjs:15289:9)
      at ChallengeSearchComponent_ngx_typed_js_5_Template (../../../ng:/ChallengeSearchComponent.js:13:73)
      at executeTemplate (../../../node_modules/@angular/core/fesm2020/core.mjs:12125:9)
      at refreshView (../../../node_modules/@angular/core/fesm2020/core.mjs:11988:13)
      at refreshEmbeddedViews (../../../node_modules/@angular/core/fesm2020/core.mjs:13038:17)

    console.error
      NG0303: Can't bind to 'typeSpeed' since it isn't a known property of 'ngx-typed-js' (used in the 'ChallengeSearchComponent' component template).
      1. If 'ngx-typed-js' is an Angular component and it has the 'typeSpeed' input, then verify that it is a part of an @NgModule where this component is declared.
      2. If 'ngx-typed-js' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
      3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

      at reportUnknownPropertyError (../../../node_modules/@angular/core/fesm2020/core.mjs:7506:17)
      at handleUnknownPropertyError (../../../node_modules/@angular/core/fesm2020/core.mjs:7499:5)
      at elementPropertyInternal (../../../node_modules/@angular/core/fesm2020/core.mjs:12520:17)
      at ɵɵproperty (../../../node_modules/@angular/core/fesm2020/core.mjs:15289:9)
      at ChallengeSearchComponent_ngx_typed_js_5_Template (../../../ng:/ChallengeSearchComponent.js:13:86)
      at executeTemplate (../../../node_modules/@angular/core/fesm2020/core.mjs:12125:9)
      at refreshView (../../../node_modules/@angular/core/fesm2020/core.mjs:11988:13)
      at refreshEmbeddedViews (../../../node_modules/@angular/core/fesm2020/core.mjs:13038:17)

    console.error
      NG0303: Can't bind to 'backSpeed' since it isn't a known property of 'ngx-typed-js' (used in the 'ChallengeSearchComponent' component template).
      1. If 'ngx-typed-js' is an Angular component and it has the 'backSpeed' input, then verify that it is a part of an @NgModule where this component is declared.
      2. If 'ngx-typed-js' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
      3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

      at reportUnknownPropertyError (../../../node_modules/@angular/core/fesm2020/core.mjs:7506:17)
      at handleUnknownPropertyError (../../../node_modules/@angular/core/fesm2020/core.mjs:7499:5)
      at elementPropertyInternal (../../../node_modules/@angular/core/fesm2020/core.mjs:12520:17)
      at ɵɵproperty (../../../node_modules/@angular/core/fesm2020/core.mjs:15289:9)
      at ChallengeSearchComponent_ngx_typed_js_5_Template (../../../ng:/ChallengeSearchComponent.js:14:10)
      at executeTemplate (../../../node_modules/@angular/core/fesm2020/core.mjs:12125:9)
      at refreshView (../../../node_modules/@angular/core/fesm2020/core.mjs:11988:13)
      at refreshEmbeddedViews (../../../node_modules/@angular/core/fesm2020/core.mjs:13038:17)

 PASS   web-home  libs/challenge-registry/home/src/lib/home.component.spec.ts
-----------------------------------------|---------|----------|---------|---------|-------------------
File                                     | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------------------------------|---------|----------|---------|---------|-------------------
All files                                |     100 |      100 |     100 |     100 |                   
 lib                                     |     100 |      100 |     100 |     100 |                   
  home.component.html                    |     100 |      100 |     100 |     100 |                   
  home.component.ts                      |     100 |      100 |     100 |     100 |                   
 lib/challenge-host-list                 |     100 |      100 |     100 |     100 |                   
  challenge-host-list.component.html     |     100 |      100 |     100 |     100 |                   
  challenge-host-list.component.ts       |     100 |      100 |     100 |     100 |                   
 lib/challenge-registration              |     100 |      100 |     100 |     100 |                   
  challenge-registration.component.html  |     100 |      100 |     100 |     100 |                   
  challenge-registration.component.ts    |     100 |      100 |     100 |     100 |                   
 lib/challenge-search                    |     100 |      100 |     100 |     100 |                   
  challenge-search.component.html        |     100 |      100 |     100 |     100 |                   
  challenge-search.component.ts          |     100 |      100 |     100 |     100 |                   
 lib/featured-challenge-list             |     100 |      100 |     100 |     100 |                   
  featured-challenge-list.component.html |     100 |      100 |     100 |     100 |                   
  featured-challenge-list.component.ts   |     100 |      100 |     100 |     100 |                   
 lib/sponsor-list                        |     100 |      100 |     100 |     100 |                   
  sponsor-list.component.html            |     100 |      100 |     100 |     100 |                   
  sponsor-list.component.ts              |     100 |      100 |     100 |     100 |                   
 lib/statistics-viewer                   |     100 |      100 |     100 |     100 |                   
  statistics-viewer.component.html       |     100 |      100 |     100 |     100 |                   
  statistics-viewer.component.ts         |     100 |      100 |     100 |     100 |                   
 lib/topics-viewer                       |     100 |      100 |     100 |     100 |                   
  topics-viewer.component.html           |     100 |      100 |     100 |     100 |                   
  topics-viewer.component.ts             |     100 |      100 |     100 |     100 |                   
-----------------------------------------|---------|----------|---------|---------|-------------------

Test Suites: 8 passed, 8 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        4.377 s
Ran all test suites.

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target test for project challenge-registry-home (43ms)
 
   Nx read the output from the cache instead of running the command for 1 out of 1 tasks.
 
   See Nx Cloud run details at https://nx.app/runs/XZIPezk1fWb
```

**Comment by tschaffter** [comment]
@rrchai Is `nx test challenge-registry-home` failing for you too? If yes, could you have a look? This is currently blocking me from push a feature branch.

All the errors are related to `ngx-typed-js`. I know we had issue with this library in the past but nothing I remember help. At least this time searching for `ngx-typed-js` among the ticket will return a result (this ticket). :)

- I checked whether [ngx-typed-js](https://www.npmjs.com/package/ngx-typed-js) had been recently updated, but the latest release was 9 mo ago and we are using it (`v2.1.1`).
- The unit tests imports `NgxTypedJsModule`.

What is weird is the following errors, which looks like `ngx-typed-js` has internal issues:

```console
    console.error
      NG0303: Can't bind to 'backSpeed' since it isn't a known property of 'ngx-typed-js' (used in the 'ChallengeSearchComponent' component template).
      1. If 'ngx-typed-js' is an Angular component and it has the 'backSpeed' input, then verify that it is a part of an @NgModule where this component is declared.
      2. If 'ngx-typed-js' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
      3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
```

**Comment by tschaffter** [comment]
UPDATE: I realize that the return code of `nx test challenge-registry-home` is 0 and thus is considered a success despite the error messages displayed. This is likely why the errors have not been detected when pushing to `main`. I fixed another issue and was finally able to push my feature branch. However, it would be great if we could fix this issue.
