### ISSUE TITLE
Upgrade openapi-validator

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#953]
We are using [IBM's openapi-validator](https://github.com/IBM/openapi-validator) to lint the OAS of this project.

Renovate recommended to update the validator from 0.55.0 to 0.96.4 (we haven't updated it in a while). The update generates error related to the validator not passing a valid ruleset object to spectral, which is used under the hood for the linting.

```console
$ lint-openapi --ruleset .spectral.yaml --verbose build/user.openapi.yaml --debug
'lodash/isPlainObject' is imported by lodash/isPlainObject?commonjs-external, but could not be resolved – treating it as an external dependency
'lodash/isEqual' is imported by lodash/isEqual?commonjs-external, but could not be resolved – treating it as an external dependency
'lodash/uniqWith' is imported by lodash/uniqWith?commonjs-external, but could not be resolved – treating it as an external dependency
'lodash/pickBy' is imported by lodash/pickBy?commonjs-external, but could not be resolved – treating it as an external dependency

[Error] There was a problem with spectral.
Provided ruleset is not an object


[Error] Additional error details:

RulesetValidationError: Provided ruleset is not an object
    at assertValidRuleset (/workspaces/challenge-registry/node_modules/ibm-openapi-validator/node_modules/@stoplight/spectral-core/dist/ruleset/validation/assertions.js:12:15)
    at new Ruleset (/workspaces/challenge-registry/node_modules/ibm-openapi-validator/node_modules/@stoplight/spectral-core/dist/ruleset/ruleset.js:35:44)
    at Spectral.setRuleset (/workspaces/challenge-registry/node_modules/ibm-openapi-validator/node_modules/@stoplight/spectral-core/dist/spectral.js:66:73)
    at Object.setup (/workspaces/challenge-registry/node_modules/ibm-openapi-validator/src/spectral/spectral-validator.js:78:12)
    at async processInput (/workspaces/challenge-registry/node_modules/ibm-openapi-validator/src/cli-validator/run-validator.js:223:24) {
  code: 'invalid-ruleset-definition',
  path: []
}
```

I can lint directly with spectral using the IBM rules, however I then loose the ability to customize the rules:

```console
vscode@64ad9ee6c6c5:/workspaces/challenge-registry/libs/api-spec$ spectral lint --ruleset .spectral.yaml build/user.openapi.yaml
'lodash/isPlainObject' is imported by lodash/isPlainObject?commonjs-external, but could not be resolved – treating it as an external dependency
'lodash/isEqual' is imported by lodash/isEqual?commonjs-external, but could not be resolved – treating it as an external dependency
'lodash/uniqWith' is imported by lodash/uniqWith?commonjs-external, but could not be resolved – treating it as an external dependency
'lodash/pickBy' is imported by lodash/pickBy?commonjs-external, but could not be resolved – treating it as an external dependency

/workspaces/challenge-registry/libs/api-spec/build/user.openapi.yaml
   1:1       warning  major-version-in-path           Major version segment not present in either server URLs or paths
   1:1       warning  oas3-api-servers                OpenAPI "servers" must be present and non-empty array.
  23:20      warning  operation-id-case-convention    Operation ids must be snake case                                                             paths./users/register.post.operationId
  49:20      warning  operation-id-case-convention    Operation ids must be snake case                                                             paths./users.get.operationId
  56:30      warning  response-example-provided       Response bodies should include an example response                                           paths./users.get.responses[200].content.application/json
  72:20      warning  operation-id-case-convention    Operation ids must be snake case                                                             paths./users/{userId}.get.operationId
  89:20      warning  operation-id-case-convention    Operation ids must be snake case                                                             paths./users/{userId}.delete.operationId
  94:30      warning  response-example-provided       Response bodies should include an example response                                           paths./users/{userId}.delete.responses[200].content.application/json
 103:11      warning  string-boundary                 Should define a pattern for a valid string                                                   components.schemas.Email
 103:11      warning  string-boundary                 Should define a minLength for a valid string                                                 components.schemas.Email
 103:11      warning  string-boundary                 Should define a maxLength for a valid string                                                 components.schemas.Email
 112:15      warning  property-description            Schema property should have a non-empty description                                          components.schemas.UserCreateRequest.properties.login
 112:15      warning  string-boundary                 Should define a pattern for a valid string                                                   components.schemas.UserCreateRequest.properties.login
 112:15      warning  string-boundary                 Should define a minLength for a valid string                                                 components.schemas.UserCreateRequest.properties.login
 112:15      warning  string-boundary                 Should define a maxLength for a valid string                                                 components.schemas.UserCreateRequest.properties.login
 116:18      warning  property-description            Schema property should have a non-empty description                                          components.schemas.UserCreateRequest.properties.password
 116:18      warning  string-boundary                 Should define a pattern for a valid string                                                   components.schemas.UserCreateRequest.properties.password
 116:18      warning  string-boundary                 Should define a minLength for a valid string                                                 components.schemas.UserCreateRequest.properties.password
 116:18      warning  string-boundary                 Should define a maxLength for a valid string                                                 components.schemas.UserCreateRequest.properties.password
 119:14      warning  property-description            Schema property should have a non-empty description                                          components.schemas.UserCreateRequest.properties.name
 119:14      warning  string-boundary                 Should define a pattern for a valid string                                                   components.schemas.UserCreateRequest.properties.name
 119:14      warning  string-boundary                 Should define a minLength for a valid string                                                 components.schemas.UserCreateRequest.properties.name
 119:14      warning  string-boundary                 Should define a maxLength for a valid string                                                 components.schemas.UserCreateRequest.properties.name
 122:19        error  property-case-convention        Property names must be snake case                                                            components.schemas.UserCreateRequest.properties.avatarUrl
 122:19      warning  property-description            Schema property should have a non-empty description                                          components.schemas.UserCreateRequest.properties.avatarUrl
 122:19      warning  string-boundary                 Should define a maxLength for a valid string                                                 components.schemas.UserCreateRequest.properties.avatarUrl
 127:13      warning  property-description            Schema property should have a non-empty description                                          components.schemas.UserCreateRequest.properties.bio
 127:13      warning  string-boundary                 Should define a pattern for a valid string                                                   components.schemas.UserCreateRequest.properties.bio
 127:13      warning  string-boundary                 Should define a minLength for a valid string                                                 components.schemas.UserCreateRequest.properties.bio
 127:13      warning  string-boundary                 Should define a maxLength for a valid string                                                 components.schemas.UserCreateRequest.properties.bio
 155:13      warning  oas3-valid-schema-example       "id" property type must be integer                                                           components.schemas.UserCreateResponse.example.id
 161:18      warning  response-error-response-schema  Error container model should contain property `trace` of type string                         components.schemas.Error.properties
 161:18      warning  response-error-response-schema  Error container model must contain property `errors` which must be an array of error models  components.schemas.Error.properties
 181:16      warning  inline-property-schema          Nested objects should be defined as a $ref to a named schema.                                components.schemas.PageMetadata.properties.paging
 189:22        error  property-case-convention        Property names must be snake case                                                            components.schemas.PageMetadata.properties.totalResults
 210:15      warning  property-description            Schema property should have a non-empty description                                          components.schemas.User.properties.login
 214:14      warning  property-description            Schema property should have a non-empty description                                          components.schemas.User.properties.name
 219:19        error  property-case-convention        Property names must be snake case                                                            components.schemas.User.properties.avatarUrl
 219:19      warning  property-description            Schema property should have a non-empty description                                          components.schemas.User.properties.avatarUrl
 224:19        error  property-case-convention        Property names must be snake case                                                            components.schemas.User.properties.createdAt
 224:19      warning  property-description            Schema property should have a non-empty description                                          components.schemas.User.properties.createdAt
 227:19        error  property-case-convention        Property names must be snake case                                                            components.schemas.User.properties.updatedAt
 227:19      warning  property-description            Schema property should have a non-empty description                                          components.schemas.User.properties.updatedAt
 230:14      warning  property-description            Schema property should have a non-empty description                                          components.schemas.User.properties.type
 233:13      warning  property-description            Schema property should have a non-empty description                                          components.schemas.User.properties.bio
 259:19      warning  array-boundary                  Array schemas should define a numeric minItems field                                         components.schemas.UsersPage.allOf[1].properties.users
 259:19      warning  array-boundary                  Array schemas should define a numeric maxItems field                                         components.schemas.UsersPage.allOf[1].properties.users
 268:17      warning  description-mentions-json       Schema descriptions should avoid mentioning "JSON"                                           components.schemas.EmptyObject
 297:16  information  parameter-case-convention       Query parameter names must be snake case                                                     components.parameters.pageNumber
 306:14  information  parameter-case-convention       Query parameter names must be snake case                                                     components.parameters.pageSize
 315:12  information  parameter-case-convention       Path parameter names must be snake case                                                      components.parameters.userId

✖ 51 problems (5 errors, 43 warnings, 3 infos, 0 hints)
```

I reported this error [here](https://github.com/IBM/openapi-validator/issues/521).

**Comment by tschaffter** [comment]
## 2022-12-14

Tried again but bumped into the same issues as reported above.

**Comment by tschaffter** [comment]
Moving to Sprint 23.03
